# Generated by Django 3.2 on 2021-05-25 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import goondirApp.middleware.current_user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGlucoseMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_glucose_ID', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=goondirApp.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BpMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_ID', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=goondirApp.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=goondirApp.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oxymeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_oxymeter_ID', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=goondirApp.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15, null=True)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('DOB', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('medicare_number', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=goondirApp.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'medicare_number', 'DOB')},
            },
        ),
        migrations.CreateModel(
            name='WeighScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigh_scale_ID', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=goondirApp.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_serial_ID', models.CharField(max_length=15)),
                ('tablet_imei', models.IntegerField(max_length=15)),
                ('sim_number', models.IntegerField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=goondirApp.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_survey_date', models.DateField()),
                ('survey_status', models.CharField(max_length=20)),
                ('start_of_VHS', models.DateField()),
                ('VHS_family', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=goondirApp.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDeviceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_glucose_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goondirApp.bloodglucosemonitor')),
                ('bp_monitor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goondirApp.bpmonitor')),
                ('created_by', models.ForeignKey(default=goondirApp.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medical_branch_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goondirApp.medicalbranch')),
                ('oxymeter_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goondirApp.oxymeter')),
                ('patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goondirApp.patient')),
                ('survey_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goondirApp.survey')),
                ('tablet_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goondirApp.tablet')),
                ('weigh_scale_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goondirApp.weighscale')),
            ],
        ),
    ]
